services:

  # LDAP Services
  openldap:
      image: osixia/openldap
      environment:
        LDAP_DOMAIN: "alfresco.org"
        LDAP_BASE_DN: "dc=alfresco,dc=org"
        LDAP_ADMIN_PASSWORD: "admin"
        LDAP_TLS: false
      command: [ --copy-service ]
      volumes:
          - ./ldap/bootstrap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/bootstrap.ldif

  phpldapadmin:
      image: osixia/phpldapadmin
      environment:
        PHPLDAPADMIN_LDAP_HOSTS: "openldap"
        PHPLDAPADMIN_HTTPS=false:
      links:
          - openldap
      depends_on:
          - openldap
      ports:
          - 8088:80           

  # ACS Services
  alfresco:
    build:
      context: ./alfresco
      args:
        ALFRESCO_TAG: ${ALFRESCO_TAG}    
    environment:
      JAVA_TOOL_OPTIONS: >-
        -Dencryption.keystore.type=JCEKS
        -Dencryption.cipherAlgorithm=DESede/CBC/PKCS5Padding
        -Dencryption.keyAlgorithm=DESede
        -Dencryption.keystore.location=/usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore
        -Dmetadata-keystore.password=mp6yc0UD9e
        -Dmetadata-keystore.aliases=metadata
        -Dmetadata-keystore.metadata.password=oKIWzVdEdA
        -Dmetadata-keystore.metadata.algorithm=DESede
      JAVA_OPTS: >-
        -Ddb.driver=org.postgresql.Driver
        -Ddb.username=alfresco
        -Ddb.password=alfresco
        -Ddb.url=jdbc:postgresql://postgres:5432/alfresco 
        -Dsolr.host=solr6
        -Dsolr.port=8983
        -Dsolr.secureComms=secret
        -Dsolr.sharedSecret=pc8wlqfok3c 
        -Dsolr.base.url=/solr
        -Dindex.subsystem.name=solr6  
        -Dshare.host=127.0.0.1
        -Dshare.port=8080 
        -Dalfresco.host=localhost
        -Dalfresco.port=8080
        -Daos.baseUrlOverwrite=http://localhost:8080/alfresco/aos
        -Dmessaging.broker.url="failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true"
        -Ddeployment.method=DOCKER_COMPOSE
        -DlocalTransform.core-aio.url=http://transform-core-aio:8090/
        -Dcsrf.filter.enabled=false
        -Dauthentication.chain=alfrescoNtlm1:alfrescoNtlm,ldap1:ldap
        -Dsynchronization.allowDeletions=false
        -Dldap.authentication.active=true
        -Dldap.authentication.java.naming.security.authentication=simple
        -Dldap.authentication.allowGuestLogin=false
        -Dldap.authentication.userNameFormat="cn=%s,ou=users,dc=alfresco,dc=org"
        -Dldap.authentication.java.naming.provider.url=ldap://openldap:389
        -Dldap.authentication.defaultAdministratorUserNames="cn=admin,dc=alfresco,dc=org"
        -Dldap.authentication.authenticateFTP=false
        -Dldap.synchronization.active=true
        -Dldap.synchronization.java.naming.security.authentication=simple
        -Dldap.synchronization.java.naming.security.principal="cn=admin,dc=alfresco,dc=org"
        -Dldap.synchronization.java.naming.security.credentials=admin
        -Dldap.synchronization.groupSearchBase="ou=groups,dc=alfresco,dc=org"
        -Dldap.synchronization.userSearchBase="ou=users,dc=alfresco,dc=org"
        -Dldap.synchronization.defaultHomeFolderProvider=userHomesHomeFolderProvider
        -Dldap.synchronization.queryBatchSize=10
        -Dldap.synchronization.groupQuery="(objectclass=posixGroup)"
        -Dldap.synchronization.groupMemberAttributeName=memberUid
        -DactivitiRepoConnector.enabled=true
        -Dactiviti.domain=http://activiti:8080
        -Dactiviti.secret=secret
        -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80

  transform-core-aio:
    image: alfresco/alfresco-transform-core-aio:${TRANSFORM_ENGINE_TAG}
    environment:
      JAVA_OPTS: >-
        -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80

  share:
    build:
      context: ./share
      args:
        SHARE_TAG: ${SHARE_TAG}
    environment:
      REPO_HOST: "alfresco"
      REPO_PORT: "8080"
      JAVA_OPTS: >-
        -XX:MinRAMPercentage=50
        -XX:MaxRAMPercentage=80
        -Dalfresco.host=localhost
        -Dalfresco.port=8080
        -Dalfresco.context=alfresco
        -Dalfresco.protocol=http

  postgres:
    image: postgres:${POSTGRES_TAG}
    environment:
      - POSTGRES_PASSWORD=alfresco
      - POSTGRES_USER=alfresco
      - POSTGRES_DB=alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG

  solr6:
    image: alfresco/alfresco-search-services:${SEARCH_TAG}
    environment:
      SOLR_ALFRESCO_HOST: "alfresco"
      SOLR_ALFRESCO_PORT: "8080"
      SOLR_SOLR_HOST: "solr6"
      SOLR_SOLR_PORT: "8983"
      SOLR_CREATE_ALFRESCO_DEFAULTS: "alfresco,archive"
      ALFRESCO_SECURE_COMMS: "secret"
      SOLR_OPTS: >-
        -Dalfresco.secureComms.secret=pc8wlqfok3c

  activemq:
    image: alfresco/alfresco-activemq:${ACTIVEMQ_TAG}

  proxy:
    image: alfresco/alfresco-acs-nginx:${ACS_NGINX_TAG}
    depends_on:
      - alfresco  
    environment:  
      - DISABLE_SYNCSERVICE=true   
      - DISABLE_ADW=true  
      - DISABLE_CONTROL_CENTER=true  
      - USE_SSL=false
    ports:
      - "8080:8080"
    links:  
      - alfresco 
      - share 

  # APS Services
  activiti:
      image: alfresco/process-services:${APS_TAG}
      mem_limit: 1500m
      depends_on:
          -  pgactiviti
      environment:
          JAVA_OPTS: " -Xms256m -Xmx1024m"
          ACTIVITI_DATASOURCE_URL: "jdbc:postgresql://pgactiviti:5432/activiti"
          ACTIVITI_DATASOURCE_DRIVER: "org.postgresql.Driver"
          ACTIVITI_HIBERNATE_DIALECT: "org.hibernate.dialect.PostgreSQLDialect"
          ACTIVITI_CSRF_DISABLED: "true"
          ACTIVITI_REVIEW_WORKFLOWS_ENABLED: "true"
      volumes:
          - ./activiti/license/activiti.lic:/usr/local/tomcat/lib/activiti.lic:ro
          - ./activiti/ldap/activiti-ldap.properties:/usr/local/tomcat/webapps/activiti-app/WEB-INF/classes/META-INF/activiti-app/activiti-ldap.properties
      ports:
          - 9090:8080

  activiti-admin:
      image: alfresco/process-services-admin:${APS_TAG}
      mem_limit: 600m
      depends_on:
          - pgactiviti
      environment:
          JAVA_OPTS: " -Xms256m -Xmx512m"
          ACTIVITI_ADMIN_DATASOURCE_URL:  "jdbc:postgresql://pgactiviti:5432/activitiadmin"
          ACTIVITI_DATASOURCE_DRIVER: "org.postgresql.Driver"
          ACTIVITI_HIBERNATE_DIALECT: "org.hibernate.dialect.PostgreSQLDialect"
          ACTIVITI_ADMIN_REST_APP_HOST: "http://activiti"
          ACTIVITI_ADMIN_REST_APP_PORT: 8080
      ports:
          - 9091:8080

  pgactiviti:
      image: postgres:${POSTGRES_TAG}
      mem_limit: 512m
      environment:
          - POSTGRES_PASSWORD=alfresco
          - POSTGRES_USER=alfresco
          - POSTGRES_DB=activiti
      command: postgres -c max_connections=300 -c log_min_messages=LOG
      volumes:
          - ./activiti/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
